[toolchain]

[features]
resolution = true
skip-lint = false

[registry]
url = "https://api.apr.dev"

[programs.devnet]
game_battle = "C5XKtCrPq3GmZKjUj4uVcHWAQgUZuQC9Pz3jjxd9Mt53"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/raigal/my-solana-wallet/mykeypair.json"

[scripts]
test = "cargo test-bpf"
init = "/scripts/init.js"
